name: kernel_gateway_docs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - sphinx_rtd_theme
  - pillow
  - pip
  - pip:
      - myst_parser
      - readthedocs-sphinx-ext
